---
title: "Compensatory mutations manuscript: Index page"
author: "jpjh"
date: "compiled Feb 2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Experimental measurements of relative fitness, plasmid cost, etc

1. **[Knockout fitness (`COMPMUT_exp_1_knockouts.Rmd`)](COMPMUT_exp_1_knockouts.md)**
2. **[Plasmid mutant fitness (`COMPMUT_exp_2_plasmids.Rmd`)](COMPMUT_exp_2_plasmids.md)**
3. **[Knockout and plasmid mutant fitness (`COMPMUT_exp_3_knopla.Rmd`)](COMPMUT_exp_3_knopla.md)**
4. **[Fitness of strains expressing of PQBR57_0059 variants *in trans* (`COMPMUT_exp_4_PQ57-59.Rmd`)](COMPMUT_exp_4_PQ57-59.md)**
5. **[Fitness of strains expressing of par genes *in trans* (`COMPMUT_exp_5_par.Rmd`)](COMPMUT_exp_5_par.md)**
6. **[Dynamics of plasmid-bearing strains in the medium term (`COMPMUT_exp_6_dynamics.Rmd`)](COMPMUT_exp_6_dynamics.md)**
7. **[Growth curve experiments from expression of plasmid-upregulated genes (`COMPMUT_exp_7_growthcurves.Rmd`)](COMPMUT_exp_7_growthcurves.md)**

### RNAseq analysis

1. **[Quality control and overview analyses (`COMPMUT_RNAseq_1_QC.Rmd`)](COMPMUT_RNAseq_1_QC.md)**
2. **[Alignment of reads to reference sequences (`COMPMUT_RNAseq_2_Alignment.Rmd`)](COMPMUT_RNAseq_2_Alignment.md)**
3. **[Counting of reads mapping to features using Rsubread featurecounts (`COMPMUT_RNAseq_3_Rsubread.Rmd`)](COMPMUT_RNAseq_3_Rsubread.md)**
4. **[Analysing differential expression with edgeR (`COMPMUT_RNAseq_4_edgeR.Rmd`)](COMPMUT_RNAseq_4_edgeR.Rmd)**
5. **[Preparing files with gene information (`COMPMUT_RNAseq_5_gene_info.Rmd`)](COMPMUT_RNAseq_5_gene_info.md)**
6. **Analysis of differential expression: [Chromosomal differential expression (`COMPMUT_RNAseq_6a_analysis.Rmd`)](COMPMUT_RNAseq_6a_analysis.md). [pQBR57 differential expression (`COMPMUT_RNAseq_6b_analysis.Rmd`)](COMPMUT_RNAseq_6b_analysis.md). [pQBR103 differential expression (`COMPMUT_RNAseq_6c_analysis.Rmd`)](COMPMUT_RNAseq_6c_analysis.md)**
7. **[Identification of SOS-associated genes (`COMPMUT_RNAseq_lexA.Rmd`)](COMPMUT_RNAseq_lexA.md)**

